import {
  Link,
  QrCode,
  ScanLine,
  Code,
  CalculatorIcon as CalcIcon,
  Palette,
  Key,
  Hash,
  FileText,
  GitCompare,
  Ruler,
  Brain,
  FileCode,
} from "lucide-react";

export const tools = [
  {
    id: "snap-ai",
    name: "Snap AI",
    description: "Compare two texts and highlight differences",
    category: "AI Tools",
    icon: Brain,
  },
  {
    id: "url-shortener",
    name: "URL Shortener",
    description: "Create short, shareable links from long URLs",
    category: "Web Tools",
    icon: Link,
  },
  {
    id: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes for text, URLs, and more",
    category: "Generators",
    icon: QrCode,
  },
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Create various types of barcodes",
    category: "Generators",
    icon: ScanLine,
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON data",
    category: "Developer Tools",
    icon: Code,
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert between different units of measurement",
    category: "Utilities",
    icon: Ruler,
  },
  {
    id: "color-palette",
    name: "Color Palette Generator",
    description: "Generate beautiful color palettes for design",
    category: "Design Tools",
    icon: Palette,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure passwords with custom options",
    category: "Security Tools",
    icon: Key,
  },
  {
    id: "base64-tool",
    name: "Base64 Encoder/Decoder",
    description: "Encode and decode Base64 strings",
    category: "Developer Tools",
    icon: FileText,
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256 hashes",
    category: "Security Tools",
    icon: Hash,
  },
  {
    id: "text-diff",
    name: "Text Diff Tool",
    description: "Compare two texts and highlight differences",
    category: "Developer Tools",
    icon: GitCompare,
  },
  {
    id: "calculator",
    name: "Scientific Calculator",
    description: "Advanced calculator with scientific functions",
    category: "Math Tools",
    icon: CalcIcon,
  },
  {
    id: "markdown-previewer",
    name: "Markdown Previewer",
    description: "Write text using Markdown syntax",
    category: "Utilities",
    icon: FileCode,
  },
  {
    id: "code-beautifier-minifier",
    name: "Code Beautifier & Minifier",
    description: "A Minifier removes all unnecessary characters from code",
    category: "Developer Tools",
    icon: ScanLine,
  },
];
